### ISSUE TITLE
论文复现效果

### ISSUE THREAD

**Issue by qq7813321** [Jinfeng-Xu/FKAN-GCF#4]
█████████████ BEST ████████████████
14 Jun 21:41    INFO    Parameters: ['seed', 'reg_weight', 'grid_size', 'dropout_node', 'dropout_message', 'n_layer']=(999, 1, 4, 0.2, 0.2, 3),
Valid: recall@5: 0.1827    recall@10: 0.2705    recall@20: 0.3852    recall@50: 0.5491    ndcg@5: 0.1349    ndcg@10: 0.1663    ndcg@20: 0.1986    ndcg@50: 0.2352    map@5: 0.1064    map@10: 0.1199    map@20: 0.1295    map@50: 0.1362    precision@5: 0.0595    precision@10: 0.0438    precision@20: 0.0310    precision@50: 0.0178    ,
Test: recall@5: 0.1753    recall@10: 0.2456    recall@20: 0.3385    recall@50: 0.4760    ndcg@5: 0.1476    ndcg@10: 0.1747    ndcg@20: 0.2026    ndcg@50: 0.2356    map@5: 0.1202    map@10: 0.1344    map@20: 0.1426    map@50: 0.1486    precision@5: 0.0998    precision@10: 0.0669    precision@20: 0.0432    precision@50: 0.0234 
你好，我在复现mooc结果如上所示，请问是由于reg_weight≠1吗？还是其他原因呢？

**Comment by Jinfeng-Xu** [comment]
> █████████████ BEST ████████████████ 14 Jun 21:41 INFO Parameters: ['seed', 'reg_weight', 'grid_size', 'dropout_node', 'dropout_message', 'n_layer']=(999, 1, 4, 0.2, 0.2, 3), Valid: recall@5: 0.1827 recall@10: 0.2705 recall@20: 0.3852 recall@50: 0.5491 ndcg@5: 0.1349 ndcg@10: 0.1663 ndcg@20: 0.1986 ndcg@50: 0.2352 map@5: 0.1064 map@10: 0.1199 map@20: 0.1295 map@50: 0.1362 precision@5: 0.0595 precision@10: 0.0438 precision@20: 0.0310 precision@50: 0.0178 , Test: recall@5: 0.1753 recall@10: 0.2456 recall@20: 0.3385 recall@50: 0.4760 ndcg@5: 0.1476 ndcg@10: 0.1747 ndcg@20: 0.2026 ndcg@50: 0.2356 map@5: 0.1202 map@10: 0.1344 map@20: 0.1426 map@50: 0.1486 precision@5: 0.0998 precision@10: 0.0669 precision@20: 0.0432 precision@50: 0.0234 你好，我在复现mooc结果如上所示，请问是由于reg_weight≠1吗？还是其他原因呢？

Thanks for running our code,

It might caused by following reasons:
1. Different random seed, we utilize 5 random seed. 999 is just a default setting for ImRec
2. Noting that different GPU servers or seeds may have slightly varied results in terms of performance, which is common in deep learning.
3. Please finish a whole grid search for hyper-parameters, if you hope to get the best result (may be higher than our report, this is a common thing).

Best,
