### ISSUE TITLE
数据集的选取问题

### ISSUE THREAD

**Issue by qq7813321** [Jinfeng-Xu/FKAN-GCF#5]
你好，FourierKAN-GCF对标的是NGCF和LightGCN,为什么没有选择和它们相同的数据集，比如Gowalla，Yelp2018，Amazon-Book，是由于稀疏度的考虑吗？

假如我想在FourierKAN-GCF复现上述数据集，超参数的选择应该更偏向于LightGCN还是FourierKAN-GCF呢？比如train_batch_size等等。

**Comment by Jinfeng-Xu** [comment]
Dear qq7813321,

Many thanks for your interest.

As stated in the lightGCN paper, they also believe that NGCF has stronger representation capabilities, due to NGCF retains the feature transform and non-linear activation parts. We therefore chose two datasets with large differences, one in which NGCF could fully demonstrate its  capabilities and one in which NGCF suffers from training difficulties.

In addition, if you want to reproduce on other datasets, please perform a more complete grid search on the hyperparameters of each model to ensure a fair comparison!

Best,

**Comment by Jinfeng-Xu** [comment]
> 你好，FourierKAN-GCF对标的是NGCF和LightGCN,为什么没有选择和它们相同的数据集，比如Gowalla，Yelp2018，Amazon-Book，是由于稀疏度的考虑吗？
> 
> 假如我想在FourierKAN-GCF复现上述数据集，超参数的选择应该更偏向于LightGCN还是FourierKAN-GCF呢？比如train_batch_size等等。

Dear qq7813321,

Many thanks for your interest.

As stated in the lightGCN paper, they also believe that NGCF has stronger representation capabilities, due to NGCF retains the feature transform and non-linear activation parts. We therefore chose two datasets with large differences, one in which NGCF could fully demonstrate its capabilities and one in which NGCF suffers from training difficulties.

In addition, if you want to reproduce on other datasets, please perform a complete grid search on the hyperparameters of each model to ensure a fair comparison!

Best,
Jinfeng
